/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VENTANAS;

import java.time.LocalDateTime;
import Clases.Boleta;
import Clases.Cliente;
import Clases.Empleado;
import Clases.Producto;
import static VENTANAS.Menu.Pnl_Cambiable;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LUCERO JUAREZ
 */
public class Pnl_Boleta extends javax.swing.JPanel {

    DefaultTableModel modelo = new DefaultTableModel();
    
    public Pnl_Boleta() {
        initComponents();
        llenarTabla();        
    }
    
    private void llenarTabla(){
        
        modelo.addColumn("ID_Boleta");
        modelo.addColumn("NumBoleta");
        modelo.addColumn("IGV");
        modelo.addColumn("Cantidad");        
        modelo.addColumn("Precio_u");
        modelo.addColumn("Precion_final");
        modelo.addColumn("Fecha_Entrega");
        modelo.addColumn("ID_Cliente");
        modelo.addColumn("ID_Empleado");
        modelo.addColumn("ID_Producto");
        
        /*
        modelo.setRowCount(Menu.listaCliente.size());
        
        int i=0;
        for(Cliente obj: Menu.listaCliente){
            modelo.setValueAt(obj.getID_cliente(), i, 0);
            modelo.setValueAt(obj.getNombre(), i, 1);
            modelo.setValueAt(obj.getRUC(), i, 2);
            modelo.setValueAt(obj.getDNI(), i, 3);
            modelo.setValueAt(obj.getGenero(), i, 4);
            modelo.setValueAt(obj.getTelefono(), i, 5);
            modelo.setValueAt(obj.getDistrito(), i, 6);
            modelo.setValueAt(obj.getDireccion(), i, 7);
            
            i++;            
        }
        */
        this.tblBoleta.setModel(modelo);
        
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBoleta = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Icn_Cerrar = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPrecioU = new javax.swing.JTextField();
        txtID_Boleta = new javax.swing.JTextField();
        txtNumBoleta = new javax.swing.JTextField();
        txtID_Cliente = new javax.swing.JTextField();
        txtID_Producto = new javax.swing.JTextField();
        txtID_Empleado = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        lblIGV = new javax.swing.JLabel();
        btnPDF = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        panelRound1 = new VENTANAS.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        txtNombreCli = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();

        jButton3.setText("Buscar");

        jButton2.setText("Buscar");

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel1.setText("Empresa: MR. PAN");

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel3.setText("Telefono : 999 - 888 - 777 ");

        tblBoleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Boleta", "NumBoleta", "IGV", "Cantidad", "Precio_U", "Precio Final", "Fecha_Entrega", "ID_Cliente", "ID_Empleado", "ID_Producto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBoleta.setToolTipText("");
        tblBoleta.setGridColor(new java.awt.Color(255, 255, 255));
        tblBoleta.setOpaque(false);
        tblBoleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBoletaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBoleta);
        if (tblBoleta.getColumnModel().getColumnCount() > 0) {
            tblBoleta.getColumnModel().getColumn(0).setPreferredWidth(7);
            tblBoleta.getColumnModel().getColumn(0).setMaxWidth(7);
            tblBoleta.getColumnModel().getColumn(0).setHeaderValue("ID_Boleta");
            tblBoleta.getColumnModel().getColumn(1).setPreferredWidth(12);
            tblBoleta.getColumnModel().getColumn(1).setHeaderValue("NumBoleta");
            tblBoleta.getColumnModel().getColumn(2).setPreferredWidth(3);
            tblBoleta.getColumnModel().getColumn(2).setMaxWidth(3);
            tblBoleta.getColumnModel().getColumn(2).setHeaderValue("IGV");
            tblBoleta.getColumnModel().getColumn(3).setHeaderValue("Cantidad");
            tblBoleta.getColumnModel().getColumn(4).setHeaderValue("Precio_U");
            tblBoleta.getColumnModel().getColumn(5).setHeaderValue("Precio Final");
            tblBoleta.getColumnModel().getColumn(6).setHeaderValue("Fecha_Entrega");
            tblBoleta.getColumnModel().getColumn(7).setPreferredWidth(8);
            tblBoleta.getColumnModel().getColumn(7).setMaxWidth(8);
            tblBoleta.getColumnModel().getColumn(7).setHeaderValue("ID_Cliente");
            tblBoleta.getColumnModel().getColumn(8).setPreferredWidth(8);
            tblBoleta.getColumnModel().getColumn(8).setMaxWidth(8);
            tblBoleta.getColumnModel().getColumn(8).setHeaderValue("ID_Empleado");
            tblBoleta.getColumnModel().getColumn(9).setPreferredWidth(8);
            tblBoleta.getColumnModel().getColumn(9).setMaxWidth(8);
            tblBoleta.getColumnModel().getColumn(9).setHeaderValue("ID_Producto");
        }

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Icn_Marca.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel6.setText("Dirección : Av. Postres Urb. Canela Mz A Lote 1 ");

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel7.setText("ID_Cliente :");

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel8.setText("Correo : mrpan@gmail.com");

        Icn_Cerrar.setFont(new java.awt.Font("Roboto Light", 1, 11)); // NOI18N
        Icn_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Icn_Volver.png"))); // NOI18N
        Icn_Cerrar.setText("Volver");
        Icn_Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Icn_CerrarMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel19.setText("ID_Boleta :");

        jLabel20.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel20.setText("N° Boleta :");

        jLabel24.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel24.setText("ID_Producto:");

        jLabel26.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel26.setText("IGV:");

        jLabel27.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel27.setText("Cantidad : ");

        jLabel28.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel28.setText("ID_Vendedor:");

        jLabel31.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel31.setText("Precio Unit.: ");

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ico_agregar.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ico_editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ico_eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 22)); // NOI18N
        jLabel2.setText("Boleta electronica");

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ico_limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblIGV.setText("0.18");

        btnPDF.setBackground(new java.awt.Color(255, 255, 255));
        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ico_pdf_1.png"))); // NOI18N
        btnPDF.setText("Generar PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ico_llenar.png"))); // NOI18N
        btnBuscar.setText("Llenar(Required to generate PDF)");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        panelRound1.setBackground(new java.awt.Color(255, 134, 56));
        panelRound1.setRoundBottomLeft(5);
        panelRound1.setRoundBottomRight(5);
        panelRound1.setRoundTopLeft(5);
        panelRound1.setRoundTopRight(5);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");

        txtNombreCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombreCli.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Producto:");

        lblProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblProducto.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DNI:");

        lblDni.setBackground(new java.awt.Color(204, 204, 204));
        lblDni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDni.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Direccion:");

        lblDireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Telefono:");

        lblTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Empleado: ");

        lblEmpleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(lblDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreCli, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDni, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(5, 5, 5)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel20)
                            .addComponent(jLabel24)
                            .addComponent(jLabel7)
                            .addComponent(jLabel19))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtID_Boleta, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel31))))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPrecioU, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIGV, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtID_Empleado, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(txtNumBoleta)
                                    .addComponent(txtID_Producto)
                                    .addComponent(txtID_Cliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Icn_Cerrar)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel1))))
                        .addGap(0, 389, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Icn_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID_Boleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIGV)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(txtID_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPDF)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Icn_CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Icn_CerrarMouseClicked

        Pnl_Cambiable.removeAll();
        Pnl_Cambiable.revalidate();
        Pnl_Cambiable.repaint();
    }//GEN-LAST:event_Icn_CerrarMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        if(tblBoleta.getSelectedRow()>=0){
            
                Boleta b = new Boleta();

                b.setID_Boleta(txtID_Boleta.getText());
                b.setNroBoleta(txtNumBoleta.getText());
                b.setCantidad(Integer.parseInt(txtCantidad.getText()));
                b.setPrecioU(Double.valueOf(txtPrecioU.getText()));
                b.setID_Cliente(txtID_Cliente.getText());
                b.setID_Producto(txtID_Producto.getText());
                b.setID_Empleado(txtID_Empleado.getText());



                try {
                    b.editar(b);
                    limpiarCampos();
                    limpiarTabla();
                    mostrar();
                } catch (SQLException ex) {
                    Logger.getLogger(Pnl_Cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
        }else{
            JOptionPane.showMessageDialog(null, "Primero debe seleccionar una boleta.","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(tblBoleta.getSelectedRow()>=0){ //Debe seleccionar una fila, sino salta una alerta.
        
        
        Boleta b = new Boleta();
        
        String indice_eliminar = (String) tblBoleta.getValueAt(tblBoleta.getSelectedRow(), 0);
        
            b.setID_Boleta(indice_eliminar);

            if(JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar este registro?","ADVERTENCIA",JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION){
                try {       
                    
                    b.eliminar(b);

                    limpiarCampos();
                    limpiarTabla();
                    mostrar();

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Debe seleccionar un registro.");
                    Logger.getLogger(Pnl_Cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        
        
        }else{
            JOptionPane.showMessageDialog(null, "Primero debe seleccionar una fila.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    public static Date fechaActual(){
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-YYYY");
        return fecha;        
    }
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Boleta objBoleta = new Boleta();
        objBoleta.setID_Boleta(txtID_Boleta.getText());
        objBoleta.setNroBoleta(txtNumBoleta.getText());
        objBoleta.setIGV(Double.valueOf(lblIGV.getText()));
        objBoleta.setCantidad(Integer.parseInt(txtCantidad.getText()));
        objBoleta.setPrecioU(Double.valueOf(txtPrecioU.getText()));
        objBoleta.setPrecioF(Integer.parseInt(txtCantidad.getText())*Double.valueOf(txtPrecioU.getText()));
        objBoleta.setFechaEntrega(fechaActual());
        objBoleta.setID_Cliente(txtID_Cliente.getText());
        objBoleta.setID_Empleado(txtID_Empleado.getText());
        objBoleta.setID_Producto(txtID_Producto.getText());
        
        System.out.println(objBoleta);
        
        try {
            objBoleta.insertar(objBoleta);
            limpiarCampos();
            limpiarTabla();
            mostrar();
        } catch (SQLException ex) {
            Logger.getLogger(Pnl_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
            
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblBoletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBoletaMouseClicked
        
        String id = (String) tblBoleta.getValueAt(tblBoleta.getSelectedRow(), 0);
        String numBoleta = (String) tblBoleta.getValueAt(tblBoleta.getSelectedRow(), 1);
        String igv = (String) tblBoleta.getValueAt(tblBoleta.getSelectedRow(), 2);
        String cantidad = (String) tblBoleta.getValueAt(tblBoleta.getSelectedRow(), 3);
        String precioU = (String) tblBoleta.getValueAt(tblBoleta.getSelectedRow(), 4);
        String precioF = (String) tblBoleta.getValueAt(tblBoleta.getSelectedRow(), 5);   
        String fechaEntrega = (String) tblBoleta.getValueAt(tblBoleta.getSelectedRow(), 6);        
        String ID_Cliente = (String) tblBoleta.getValueAt(tblBoleta.getSelectedRow(), 7);
        String ID_Empleado = (String) tblBoleta.getValueAt(tblBoleta.getSelectedRow(), 8);
        String ID_Producto = (String) tblBoleta.getValueAt(tblBoleta.getSelectedRow(), 9);
                     
        
        
        try {
            
            txtID_Boleta.setText(id);
            txtNumBoleta.setText(numBoleta);
            txtCantidad.setText(cantidad);
            txtPrecioU.setText(precioU);
            txtID_Cliente.setText(ID_Cliente);
            txtID_Empleado.setText(ID_Empleado);
            txtID_Producto.setText(ID_Producto);
            
            
        } catch (Exception e) {
            System.out.println("Error en Editar: "+e.getMessage());
        }
        
        
    }//GEN-LAST:event_tblBoletaMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        pdf();
    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarCliente();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void limpiarTabla(){
        //Eliminar todas las tablas
        int elimTotal = tblBoleta.getRowCount();
        for (int i = elimTotal-1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
    
    private void limpiarCampos(){
        txtID_Boleta.setText("");
        txtNumBoleta.setText("");
        txtCantidad.setText("");
        txtPrecioU.setText("");
        txtID_Cliente.setText("");
        txtID_Empleado.setText("");
        txtID_Producto.setText("");
        
        lblProducto.setText("");
        txtNombreCli.setText("");
        lblDni.setText("");
        lblTelefono.setText("");     
        lblEmpleado.setText("");
        lblDireccion.setText("");
        txtID_Boleta.grabFocus();
    }
    
    private void mostrar(){
        Boleta b = new Boleta();

        try {
            List<Boleta> boletas = b.obtenerTodos();

            //Iterator<Cliente> it = Menu.listaCliente.iterator();

            Iterator<Boleta> it = boletas.iterator();

            //Mostrar Datos Almacenados previamente
            while(it.hasNext()){
                b = it.next();
                String agregar[] = new String[10];
                agregar[0] = b.getID_Boleta();
                agregar[1] = b.getNroBoleta();
                agregar[2] = String.valueOf(b.getIGV());
                agregar[3] = String.valueOf(b.getCantidad());
                agregar[4] = String.valueOf(b.getPrecioU());
                agregar[5] = String.valueOf(b.getPrecioF());
                agregar[6] = String.valueOf(b.getFechaEntrega());
                agregar[7] = b.getID_Cliente();
                agregar[8] = b.getID_Empleado();
                agregar[9] = b.getID_Producto();

                modelo.addRow(agregar);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Pnl_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void buscarCliente(){        
        Cliente c1 = new Cliente();
        Producto p = new Producto();
        Empleado e = new Empleado();
        
        String nombrecli = txtID_Cliente.getText();
        String idpro = txtID_Producto.getText();
        String idemp = txtID_Empleado.getText();
        
        
        
        try{
            c1 = c1.obtener(nombrecli); 
            p = p.obtener(idpro);
            e = e.obtener(idemp);
            if(c1.getNombre() != null){
                txtNombreCli.setText(c1.getNombre());
                lblDni.setText(c1.getDNI());
                lblTelefono.setText(c1.getTelefono());
                lblEmpleado.setText(e.getNombre());                
                lblDireccion.setText(c1.getDireccion());
                lblProducto.setText(p.getNombre());
            }else{
                System.out.println("No existen.");
            }
                     
        }catch(SQLException ex){
            System.out.println("Mensaje: "+ex.getMessage());
        }
        
        
    }
    
    private void pdf(){
        try{
            FileOutputStream archivo;
            File file = new File("src/pdf/boleta.pdf");
            archivo = new FileOutputStream(file);
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            Image img = Image.getInstance("src/IMAGENES/Icn_Marca.png");
            
            Paragraph fecha = new Paragraph();
            Font negrita = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD, BaseColor.BLACK);
            fecha.add(Chunk.NEWLINE);
            Date date = new Date();
            fecha.add("Boleta: "+(txtNumBoleta.getText())+"\n"+"Fecha: "+new SimpleDateFormat("dd-MM-yyyy").format(date)+"\n\n");
            
            PdfPTable Encabezado = new PdfPTable(4);
            Encabezado.setWidthPercentage(100);
            Encabezado.getDefaultCell().setBorder(0);
            float[] ColumnaEncabezado = new float[]{20f, 30f, 70f, 40f};
            Encabezado.setWidths(ColumnaEncabezado);
            Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
            
            Encabezado.addCell(img);
            
            
            String nom = "Panadería Mr. Pan";
            String tel = "999 - 888 - 777";
            String dir = "Av. Postres Urb. Canela Mz A Lote 1";
            
            
            Encabezado.addCell("");
            Encabezado.addCell("Nombre: "+nom+"\nTelefono: "+tel+"\nDireccion: "+dir);
            Encabezado.addCell(fecha);
            doc.add(Encabezado);
            
            Paragraph cli = new Paragraph();
            cli.add(Chunk.NEWLINE);
            cli.add("Datos del cliente: "+"\n\n");
            doc.add(cli);
            
            PdfPTable tablacli = new PdfPTable(4);
            tablacli.setWidthPercentage(100);
            tablacli.getDefaultCell().setBorder(0);
            float[] Columnacli = new float[]{20f, 50f, 30f, 40f};
            tablacli.setWidths(Columnacli);
            tablacli.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell cl1 = new PdfPCell(new Phrase("Dni", negrita));
            PdfPCell cl2 = new PdfPCell(new Phrase("Nombre", negrita));
            PdfPCell cl3 = new PdfPCell(new Phrase("Telefono", negrita));
            PdfPCell cl4 = new PdfPCell(new Phrase("Direccion", negrita));
            cl1.setBorder(0);
            cl2.setBorder(0);
            cl3.setBorder(0);
            cl4.setBorder(0);
            tablacli.addCell(cl1);
            tablacli.addCell(cl2);
            tablacli.addCell(cl3);
            tablacli.addCell(cl4);
            
            Cliente c = new Cliente();
            
            tablacli.addCell(lblDni.getText());
            tablacli.addCell(txtNombreCli.getText());
            tablacli.addCell(lblTelefono.getText());
            tablacli.addCell(lblEmpleado.getText());
            
            doc.add(tablacli);
            
            //Vendedor
            Paragraph emp = new Paragraph();
            emp.add(Chunk.NEWLINE);
            emp.add("Datos del empleado: "+"\n\n");
            doc.add(emp);
            
            PdfPTable tablaemp = new PdfPTable(2);
            tablaemp.setWidthPercentage(100);
            tablaemp.getDefaultCell().setBorder(0);
            float[] Columnaemp = new float[]{50f, 50f};
            tablaemp.setWidths(Columnaemp);
            tablaemp.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell emp1 = new PdfPCell(new Phrase("ID", negrita));
            PdfPCell emp2 = new PdfPCell(new Phrase("Nombre", negrita));
            
            emp1.setBorder(0);
            emp2.setBorder(0);
            
            tablaemp.addCell(emp1);
            tablaemp.addCell(emp2);
            
            tablaemp.addCell(lblDireccion.getText());
            tablaemp.addCell(lblEmpleado.getText());            
            
            doc.add(tablaemp);
            
            //Producto
             Paragraph prod = new Paragraph();
            prod.add(Chunk.NEWLINE);
            prod.add("Datos de producto: "+"\n\n");
            doc.add(prod);
            
            PdfPTable tablapro = new PdfPTable(4);
            tablapro.setWidthPercentage(100);
            tablapro.getDefaultCell().setBorder(0);
            float[] Columnapro = new float[]{10f, 50f, 15f, 20f};
            tablapro.setWidths(Columnapro);
            tablapro.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell pro1 = new PdfPCell(new Phrase("Nom.", negrita));
            PdfPCell pro2 = new PdfPCell(new Phrase("Cant.", negrita));
            PdfPCell pro3 = new PdfPCell(new Phrase("Precio U.", negrita));
            PdfPCell pro4 = new PdfPCell(new Phrase("Precio F.", negrita));
            
            pro1.setBorder(0);
            pro2.setBorder(0);
            pro3.setBorder(0);
            pro4.setBorder(0);
            
            pro1.setBackgroundColor(BaseColor.LIGHT_GRAY);
            pro2.setBackgroundColor(BaseColor.LIGHT_GRAY);
            pro3.setBackgroundColor(BaseColor.LIGHT_GRAY);
            pro4.setBackgroundColor(BaseColor.LIGHT_GRAY);
            
            tablapro.addCell(pro1);
            tablapro.addCell(pro2);
            tablapro.addCell(pro3);
            tablapro.addCell(pro4);
            
            Boleta b = new Boleta();
            
            /*for (int i = 0; i < 1; i++) {
                String cantidad = tblBoleta.getValueAt(i, 4).toString();
                String PrecioU = tblBoleta.getValueAt(i, 5).toString();
                String PrecioF = tblBoleta.getValueAt(i, 6).toString();                              
            }*/
            
            tablapro.addCell(lblProducto.getText());
            tablapro.addCell(txtCantidad.getText());
            tablapro.addCell(txtPrecioU.getText()); 
            tablapro.addCell(String.valueOf(Integer.parseInt(txtCantidad.getText())*Double.valueOf(txtPrecioU.getText()))); 
            
            
            doc.add(tablapro);
            
            Paragraph mensaje = new Paragraph();
            mensaje.add(Chunk.NEWLINE);
            mensaje.add("Gracias por su compra");
            mensaje.setAlignment(Element.ALIGN_CENTER);
            doc.add(mensaje);
                        
            
            doc.close();
            archivo.close();
            Desktop.getDesktop().open(file);
        }catch(DocumentException | IOException | NumberFormatException e){
            System.out.println("Mensaje: "+e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icn_Cerrar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblIGV;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblTelefono;
    private VENTANAS.PanelRound panelRound1;
    private javax.swing.JTable tblBoleta;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtID_Boleta;
    private javax.swing.JTextField txtID_Cliente;
    private javax.swing.JTextField txtID_Empleado;
    private javax.swing.JTextField txtID_Producto;
    private javax.swing.JLabel txtNombreCli;
    private javax.swing.JTextField txtNumBoleta;
    private javax.swing.JTextField txtPrecioU;
    // End of variables declaration//GEN-END:variables
}
